language: php

php:
    - 7.4

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - COMPOSER_MEMORY_LIMIT=-1
    - composer self-update

install:
    - composer install
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --with-all-dependencies; fi;

script:
    - vendor/bin/phpunit
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index.html
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index-with-es5-shim.html

matrix:
    fast_finish: true
    include:
      - php: 7.4
        env: SYMFONY_VERSION='^4.4'
